### ISSUE TITLE
django-bootstrap-datepicker-plus

### ISSUE THREAD

**Issue by tomaszkaliciak** [monim67/test#1]
Hi,
I have got a problem with your widget. When I added 
`{% block extrahead %}
{{ form.media }}
{% endblock %}`
to my base.html bootstrap buttons lost their borders.
Before:
![1](https://user-images.githubusercontent.com/14941051/40841453-d1cd9ae4-65aa-11e8-86b6-f39f0f8b803b.png)
After:
![2](https://user-images.githubusercontent.com/14941051/40841455-d3ce3a92-65aa-11e8-862f-a509847e22f2.png)
How Can i fix it?
Thank you for the hard effort you put into your work ;)

**Comment by tomaszkaliciak** [comment]
I reinstalled widget and everything is fine ;)

**Comment by monim67** [comment]
@tomaszkaliciak efforts are not possible without people submitting helpful issues we developers often overlook. The issue has been fixed and new version has been released which I guess you already received when you reinstalled 👍
